// Purpose and Main Use of the Code
// The code snippet provided is for a client program that accesses a shared memory segment created by a server. It retrieves the data written to shared memory by the server, prints it, and then cleans up by detaching from the shared memory segment and marking it for deletion.

// Libraries Used
// stdio.h: For input and output functions like printf().
// sys/ipc.h: For Inter-Process Communication (IPC) functions.
// sys/shm.h: For shared memory functions, such as shmget() and shmat().
// stdlib.h: For memory allocation, process control functions, and definitions.
// Code with Line-by-Line Explanation
// c
// Copy code
#include <stdio.h>          // Include standard I/O library for input and output functions
#include <sys/ipc.h>       // Include library for IPC (Inter-Process Communication) functions
#include <sys/shm.h>       // Include library for shared memory functions
#include <stdlib.h>        // Include standard library for memory allocation and process control

int main() {
    // Create the same key used by the server
    key_t key = ftok("shmfile", 65);  // Generate a unique key using the ftok function; "shmfile" is the pathname and 65 is a project identifier
    if (key == -1) {                   
        perror("ftok");                // Print error message if ftok fails
        exit(1);                       // Exit the program with a failure status
    }

    // Get the shared memory segment created by the server
    int shmid = shmget(key, 1024, 0666); // Access the shared memory segment created by the server with the specified key
    if (shmid == -1) {                  
        perror("shmget");              // Print error message if shmget fails
        exit(1);                       // Exit the program with a failure status
    }

    // Attach the shared memory segment to the client's address space
    char *str = (char *) shmat(shmid, NULL, 0); // Attach shared memory to the process's address space; NULL indicates that the OS will choose the address
    if (str == (char *) -1) {        
        perror("shmat");               // Print error message if shmat fails
        exit(1);                       // Exit the program with a failure status
    }

    // Read data from shared memory
    printf("Data read from memory: %s\n", str); // Print the data read from shared memory

    // Detach the shared memory segment
    if (shmdt(str) == -1) {           
        perror("shmdt");               // Print error message if shmdt fails
        exit(1);                       // Exit the program with a failure status
    }

    // Destroy the shared memory segment
    if (shmctl(shmid, IPC_RMID, NULL) == -1) { // Mark the shared memory segment for deletion using shmctl
        perror("shmctl");               // Print error message if shmctl fails
        exit(1);                       // Exit the program with a failure status
    }

    return 0;                          // Return 0 to indicate successful completion of the program
}
// Possible Questions for client.c
// What is the purpose of ftok() in this code?

// Answer: The ftok() function is used to generate a unique key for the shared memory segment based on a pathname (shmfile) and a project identifier (65). This key is crucial for the client to access the same shared memory segment that the server created.
// Explain the significance of the shmget() function.

// Answer: The shmget() function is used to access a shared memory segment. It takes the unique key generated by ftok(), the size of the segment, and the permission flags as arguments. If the segment exists, it returns its identifier; otherwise, it returns an error.
// What happens if shmat() fails?

// Answer: If shmat() fails, it returns (char *) -1, indicating that the attachment of the shared memory segment to the process's address space was unsuccessful. The code checks for this condition and prints an error message, then exits the program.
// What is the role of shmctl() in this program?

// Answer: The shmctl() function is used to control the shared memory segment. In this case, it is called with the IPC_RMID command to mark the shared memory segment for deletion, ensuring that it is removed from the system once all processes have detached from it.
// Familiar Words and Concepts
// Shared Memory: A method for inter-process communication that allows multiple processes to access a common memory space.
// Key: A unique identifier generated for the shared memory segment to enable processes to access the same memory space.
// Attach/Detach: Attaching a shared memory segment maps it into the process's address space, while detaching removes it from the address space.
